namespace LingoGen.Generator;

public static class Classes
{
    public const string Namespace = "LingoGen";

    public static string Lingo =>
        $$"""
          // <auto-generated/>

          using System.Globalization;

          namespace {{Namespace}};

          /// <summary>
          /// Static class containing all lingo entries.
          /// </summary>
          public static partial class Lingo
          {
              public static string GetLanguageCode() => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
          }
          """;

    public const string Content =
        $$"""
          // <auto-generated/>

          #nullable enable

          namespace {{Namespace}};

          /// <summary>
          /// Content that can be used to provide translations.
          /// </summary>
          public abstract class Content
          {
              /// <summary>
              /// Returns a localized string based on the current language.
              /// </summary>
              /// <returns>Returns a localized string based on the current language.</returns>
              public sealed override string ToString()
              {
                  var code = Lingo.GetLanguageCode();
                  return ToString(code) ?? $"[ No '{code}' translation for '{GetType().Name}' ]";
              }
          
              public abstract string? ToString(string languageCode);
          }
          """;
}