name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+" # Ignore tags that match the pattern v1.2.3
  pull_request:
    branches: [ main, development ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Pack
        run: dotnet pack -c Release --no-build